name: 'required-file-changes'
description: 'Checks the required file changes'
author: 'Gorkem Ercan'
inputs:
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. 
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  filePatterns:
    required: true
    description: >
      The file patterns that must be satisfied by the changes included on the pull request
  skipLabels:
    required: false
    description: >
      List of labels that this check should be skipped for  
runs:
  using: 'node16'
  main: 'dist/index.js'
